name: Bug report（Bug提交）
description: Create a report to help us improve
labels: ["bug"]
assignees:
 - xiangyu5632
body:
 - type: markdown
   attributes:
    value: |
     Thanks for taking the time to fill out this bug report!
 - type: textarea
   id: bug-description
   attributes:
    label: Describe the bug（Bug 描述）
    description: A clear and concise description of what the bug is. （用简洁、准确的语言描述Bug的情况）
   validations:
    required: true
 - type: textarea
   id: bug-reproduce
   attributes:
     label: To Reproduce（Bug 复现步骤）
     description: Steps to reproduce the behavior（描述复现Bug的步骤，第一步、第二步...）
     placeholder: "1. Go to '...'\n2. Click on '....'\n3. Scroll down to '....'\n4. See error "
 - type: textarea
   id: expectation
   attributes:
     label: Expected behavior（期望结果）
     description: A clear and concise description of what you expected to happen.（描述清楚正确的结果应该是什么样的）
 - type: textarea
   id: screenshots
   attributes:
     label: Screenshots（屏幕截图）
     description: If applicable, add screenshots to help explain your problem.（如果可能，请尽量上传Bug的屏幕截图，对解释清楚Bug非常有帮助）
 - type: textarea
   id: logs
   attributes:
     label: Logs（完整的错误日志）
     description: If applicable, add complete error logs to help analyze and resolve problems faster.（提供完整的错误日志可以帮助社区更快分析和解决问题）
 - type: textarea
   id: context
   attributes:
     label: Additional context（其他的一些补充内容）
     description: Add any other context about the problem here.（在此处添加有关该问题的任何其他上下文）