name: Custom（其他）
description: Describe others
labels: ["help wanted"]
assignees:
 - xiangyu5632
body:
 - type: textarea
   id: content
   attributes:
    label: Describe your question
    description: add some content here
   validations:
    required: true