// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lib/netstorage/data/data.proto

package netstorage_data

import (
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
	proto1 "github.com/openGemini/openGemini/lib/util/lifted/influx/meta/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SeriesKeysRequest struct {
	Db                   *string  `protobuf:"bytes,1,req,name=Db" json:"Db,omitempty"`
	PtIDs                []uint32 `protobuf:"varint,2,rep,name=PtIDs" json:"PtIDs,omitempty"`
	Measurements         []string `protobuf:"bytes,3,rep,name=Measurements" json:"Measurements,omitempty"`
	Condition            *string  `protobuf:"bytes,4,opt,name=condition" json:"condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeriesKeysRequest) Reset()         { *m = SeriesKeysRequest{} }
func (m *SeriesKeysRequest) String() string { return proto.CompactTextString(m) }
func (*SeriesKeysRequest) ProtoMessage()    {}
func (*SeriesKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaddb15866ce618, []int{0}
}
func (m *SeriesKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeriesKeysRequest.Unmarshal(m, b)
}
func (m *SeriesKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeriesKeysRequest.Marshal(b, m, deterministic)
}
func (m *SeriesKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeriesKeysRequest.Merge(m, src)
}
func (m *SeriesKeysRequest) XXX_Size() int {
	return xxx_messageInfo_SeriesKeysRequest.Size(m)
}
func (m *SeriesKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SeriesKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SeriesKeysRequest proto.InternalMessageInfo

func (m *SeriesKeysRequest) GetDb() string {
	if m != nil && m.Db != nil {
		return *m.Db
	}
	return ""
}

func (m *SeriesKeysRequest) GetPtIDs() []uint32 {
	if m != nil {
		return m.PtIDs
	}
	return nil
}

func (m *SeriesKeysRequest) GetMeasurements() []string {
	if m != nil {
		return m.Measurements
	}
	return nil
}

func (m *SeriesKeysRequest) GetCondition() string {
	if m != nil && m.Condition != nil {
		return *m.Condition
	}
	return ""
}

type SeriesKeysResponse struct {
	Series               []string `protobuf:"bytes,1,rep,name=Series" json:"Series,omitempty"`
	Err                  *string  `protobuf:"bytes,2,opt,name=Err" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeriesKeysResponse) Reset()         { *m = SeriesKeysResponse{} }
func (m *SeriesKeysResponse) String() string { return proto.CompactTextString(m) }
func (*SeriesKeysResponse) ProtoMessage()    {}
func (*SeriesKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaddb15866ce618, []int{1}
}
func (m *SeriesKeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeriesKeysResponse.Unmarshal(m, b)
}
func (m *SeriesKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeriesKeysResponse.Marshal(b, m, deterministic)
}
func (m *SeriesKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeriesKeysResponse.Merge(m, src)
}
func (m *SeriesKeysResponse) XXX_Size() int {
	return xxx_messageInfo_SeriesKeysResponse.Size(m)
}
func (m *SeriesKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SeriesKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SeriesKeysResponse proto.InternalMessageInfo

func (m *SeriesKeysResponse) GetSeries() []string {
	if m != nil {
		return m.Series
	}
	return nil
}

func (m *SeriesKeysResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type ShowTagKeysRequest struct {
	Db                   *string  `protobuf:"bytes,1,req,name=Db" json:"Db,omitempty"`
	PtIDs                []uint32 `protobuf:"varint,2,rep,name=PtIDs" json:"PtIDs,omitempty"`
	Measurements         []string `protobuf:"bytes,3,rep,name=Measurements" json:"Measurements,omitempty"`
	Condition            *string  `protobuf:"bytes,4,opt,name=condition" json:"condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowTagKeysRequest) Reset()         { *m = ShowTagKeysRequest{} }
func (m *ShowTagKeysRequest) String() string { return proto.CompactTextString(m) }
func (*ShowTagKeysRequest) ProtoMessage()    {}
func (*ShowTagKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaddb15866ce618, []int{2}
}
func (m *ShowTagKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowTagKeysRequest.Unmarshal(m, b)
}
func (m *ShowTagKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowTagKeysRequest.Marshal(b, m, deterministic)
}
func (m *ShowTagKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowTagKeysRequest.Merge(m, src)
}
func (m *ShowTagKeysRequest) XXX_Size() int {
	return xxx_messageInfo_ShowTagKeysRequest.Size(m)
}
func (m *ShowTagKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowTagKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShowTagKeysRequest proto.InternalMessageInfo

func (m *ShowTagKeysRequest) GetDb() string {
	if m != nil && m.Db != nil {
		return *m.Db
	}
	return ""
}

func (m *ShowTagKeysRequest) GetPtIDs() []uint32 {
	if m != nil {
		return m.PtIDs
	}
	return nil
}

func (m *ShowTagKeysRequest) GetMeasurements() []string {
	if m != nil {
		return m.Measurements
	}
	return nil
}

func (m *ShowTagKeysRequest) GetCondition() string {
	if m != nil && m.Condition != nil {
		return *m.Condition
	}
	return ""
}

type ShowTagKeysResponse struct {
	TagKeys              []string `protobuf:"bytes,1,rep,name=TagKeys" json:"TagKeys,omitempty"`
	Err                  *string  `protobuf:"bytes,2,opt,name=Err" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowTagKeysResponse) Reset()         { *m = ShowTagKeysResponse{} }
func (m *ShowTagKeysResponse) String() string { return proto.CompactTextString(m) }
func (*ShowTagKeysResponse) ProtoMessage()    {}
func (*ShowTagKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaddb15866ce618, []int{3}
}
func (m *ShowTagKeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowTagKeysResponse.Unmarshal(m, b)
}
func (m *ShowTagKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowTagKeysResponse.Marshal(b, m, deterministic)
}
func (m *ShowTagKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowTagKeysResponse.Merge(m, src)
}
func (m *ShowTagKeysResponse) XXX_Size() int {
	return xxx_messageInfo_ShowTagKeysResponse.Size(m)
}
func (m *ShowTagKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowTagKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShowTagKeysResponse proto.InternalMessageInfo

func (m *ShowTagKeysResponse) GetTagKeys() []string {
	if m != nil {
		return m.TagKeys
	}
	return nil
}

func (m *ShowTagKeysResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type CreateDataBaseRequest struct {
	Db                   *string  `protobuf:"bytes,1,req,name=Db" json:"Db,omitempty"`
	Pt                   *uint32  `protobuf:"varint,2,req,name=pt" json:"pt,omitempty"`
	Rp                   *string  `protobuf:"bytes,3,req,name=rp" json:"rp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDataBaseRequest) Reset()         { *m = CreateDataBaseRequest{} }
func (m *CreateDataBaseRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDataBaseRequest) ProtoMessage()    {}
func (*CreateDataBaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaddb15866ce618, []int{4}
}
func (m *CreateDataBaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDataBaseRequest.Unmarshal(m, b)
}
func (m *CreateDataBaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDataBaseRequest.Marshal(b, m, deterministic)
}
func (m *CreateDataBaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDataBaseRequest.Merge(m, src)
}
func (m *CreateDataBaseRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDataBaseRequest.Size(m)
}
func (m *CreateDataBaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDataBaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDataBaseRequest proto.InternalMessageInfo

func (m *CreateDataBaseRequest) GetDb() string {
	if m != nil && m.Db != nil {
		return *m.Db
	}
	return ""
}

func (m *CreateDataBaseRequest) GetPt() uint32 {
	if m != nil && m.Pt != nil {
		return *m.Pt
	}
	return 0
}

func (m *CreateDataBaseRequest) GetRp() string {
	if m != nil && m.Rp != nil {
		return *m.Rp
	}
	return ""
}

type CreateDataBaseResponse struct {
	Err                  *string  `protobuf:"bytes,1,opt,name=Err" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDataBaseResponse) Reset()         { *m = CreateDataBaseResponse{} }
func (m *CreateDataBaseResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDataBaseResponse) ProtoMessage()    {}
func (*CreateDataBaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaddb15866ce618, []int{5}
}
func (m *CreateDataBaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDataBaseResponse.Unmarshal(m, b)
}
func (m *CreateDataBaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDataBaseResponse.Marshal(b, m, deterministic)
}
func (m *CreateDataBaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDataBaseResponse.Merge(m, src)
}
func (m *CreateDataBaseResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDataBaseResponse.Size(m)
}
func (m *CreateDataBaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDataBaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDataBaseResponse proto.InternalMessageInfo

func (m *CreateDataBaseResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type SysCtrlRequest struct {
	Mod                  *string           `protobuf:"bytes,1,req,name=Mod" json:"Mod,omitempty"`
	Param                map[string]string `protobuf:"bytes,2,rep,name=Param" json:"Param,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SysCtrlRequest) Reset()         { *m = SysCtrlRequest{} }
func (m *SysCtrlRequest) String() string { return proto.CompactTextString(m) }
func (*SysCtrlRequest) ProtoMessage()    {}
func (*SysCtrlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaddb15866ce618, []int{6}
}
func (m *SysCtrlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysCtrlRequest.Unmarshal(m, b)
}
func (m *SysCtrlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysCtrlRequest.Marshal(b, m, deterministic)
}
func (m *SysCtrlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysCtrlRequest.Merge(m, src)
}
func (m *SysCtrlRequest) XXX_Size() int {
	return xxx_messageInfo_SysCtrlRequest.Size(m)
}
func (m *SysCtrlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SysCtrlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SysCtrlRequest proto.InternalMessageInfo

func (m *SysCtrlRequest) GetMod() string {
	if m != nil && m.Mod != nil {
		return *m.Mod
	}
	return ""
}

func (m *SysCtrlRequest) GetParam() map[string]string {
	if m != nil {
		return m.Param
	}
	return nil
}

type SysCtrlResponse struct {
	Err                  *string           `protobuf:"bytes,1,req,name=Err" json:"Err,omitempty"`
	Result               map[string]string `protobuf:"bytes,2,rep,name=Result" json:"Result,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SysCtrlResponse) Reset()         { *m = SysCtrlResponse{} }
func (m *SysCtrlResponse) String() string { return proto.CompactTextString(m) }
func (*SysCtrlResponse) ProtoMessage()    {}
func (*SysCtrlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaddb15866ce618, []int{7}
}
func (m *SysCtrlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysCtrlResponse.Unmarshal(m, b)
}
func (m *SysCtrlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysCtrlResponse.Marshal(b, m, deterministic)
}
func (m *SysCtrlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysCtrlResponse.Merge(m, src)
}
func (m *SysCtrlResponse) XXX_Size() int {
	return xxx_messageInfo_SysCtrlResponse.Size(m)
}
func (m *SysCtrlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SysCtrlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SysCtrlResponse proto.InternalMessageInfo

func (m *SysCtrlResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

func (m *SysCtrlResponse) GetResult() map[string]string {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetShardSplitPointsRequest struct {
	DB                   *string  `protobuf:"bytes,1,req,name=DB" json:"DB,omitempty"`
	PtID                 *uint32  `protobuf:"varint,2,req,name=PtID" json:"PtID,omitempty"`
	ShardID              *uint64  `protobuf:"varint,3,req,name=ShardID" json:"ShardID,omitempty"`
	Idxes                []int64  `protobuf:"varint,4,rep,name=Idxes" json:"Idxes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShardSplitPointsRequest) Reset()         { *m = GetShardSplitPointsRequest{} }
func (m *GetShardSplitPointsRequest) String() string { return proto.CompactTextString(m) }
func (*GetShardSplitPointsRequest) ProtoMessage()    {}
func (*GetShardSplitPointsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaddb15866ce618, []int{8}
}
func (m *GetShardSplitPointsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShardSplitPointsRequest.Unmarshal(m, b)
}
func (m *GetShardSplitPointsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShardSplitPointsRequest.Marshal(b, m, deterministic)
}
func (m *GetShardSplitPointsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShardSplitPointsRequest.Merge(m, src)
}
func (m *GetShardSplitPointsRequest) XXX_Size() int {
	return xxx_messageInfo_GetShardSplitPointsRequest.Size(m)
}
func (m *GetShardSplitPointsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShardSplitPointsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetShardSplitPointsRequest proto.InternalMessageInfo

func (m *GetShardSplitPointsRequest) GetDB() string {
	if m != nil && m.DB != nil {
		return *m.DB
	}
	return ""
}

func (m *GetShardSplitPointsRequest) GetPtID() uint32 {
	if m != nil && m.PtID != nil {
		return *m.PtID
	}
	return 0
}

func (m *GetShardSplitPointsRequest) GetShardID() uint64 {
	if m != nil && m.ShardID != nil {
		return *m.ShardID
	}
	return 0
}

func (m *GetShardSplitPointsRequest) GetIdxes() []int64 {
	if m != nil {
		return m.Idxes
	}
	return nil
}

type GetShardSplitPointsResponse struct {
	SplitPoints          []string `protobuf:"bytes,1,rep,name=SplitPoints" json:"SplitPoints,omitempty"`
	Err                  *string  `protobuf:"bytes,2,opt,name=Err" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShardSplitPointsResponse) Reset()         { *m = GetShardSplitPointsResponse{} }
func (m *GetShardSplitPointsResponse) String() string { return proto.CompactTextString(m) }
func (*GetShardSplitPointsResponse) ProtoMessage()    {}
func (*GetShardSplitPointsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaddb15866ce618, []int{9}
}
func (m *GetShardSplitPointsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShardSplitPointsResponse.Unmarshal(m, b)
}
func (m *GetShardSplitPointsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShardSplitPointsResponse.Marshal(b, m, deterministic)
}
func (m *GetShardSplitPointsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShardSplitPointsResponse.Merge(m, src)
}
func (m *GetShardSplitPointsResponse) XXX_Size() int {
	return xxx_messageInfo_GetShardSplitPointsResponse.Size(m)
}
func (m *GetShardSplitPointsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShardSplitPointsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetShardSplitPointsResponse proto.InternalMessageInfo

func (m *GetShardSplitPointsResponse) GetSplitPoints() []string {
	if m != nil {
		return m.SplitPoints
	}
	return nil
}

func (m *GetShardSplitPointsResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type DeleteRequest struct {
	DB                   *string  `protobuf:"bytes,1,req,name=DB" json:"DB,omitempty"`
	Rp                   *string  `protobuf:"bytes,2,opt,name=Rp" json:"Rp,omitempty"`
	Mst                  *string  `protobuf:"bytes,3,opt,name=Mst" json:"Mst,omitempty"`
	ShardIDs             []uint64 `protobuf:"varint,4,rep,name=ShardIDs" json:"ShardIDs,omitempty"`
	DeleteType           *int32   `protobuf:"varint,5,req,name=DeleteType" json:"DeleteType,omitempty"`
	PtId                 *uint32  `protobuf:"varint,6,opt,name=PtId" json:"PtId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaddb15866ce618, []int{10}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetDB() string {
	if m != nil && m.DB != nil {
		return *m.DB
	}
	return ""
}

func (m *DeleteRequest) GetRp() string {
	if m != nil && m.Rp != nil {
		return *m.Rp
	}
	return ""
}

func (m *DeleteRequest) GetMst() string {
	if m != nil && m.Mst != nil {
		return *m.Mst
	}
	return ""
}

func (m *DeleteRequest) GetShardIDs() []uint64 {
	if m != nil {
		return m.ShardIDs
	}
	return nil
}

func (m *DeleteRequest) GetDeleteType() int32 {
	if m != nil && m.DeleteType != nil {
		return *m.DeleteType
	}
	return 0
}

func (m *DeleteRequest) GetPtId() uint32 {
	if m != nil && m.PtId != nil {
		return *m.PtId
	}
	return 0
}

type DeleteResponse struct {
	Err                  *string  `protobuf:"bytes,1,opt,name=Err" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaddb15866ce618, []int{11}
}
func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type ShowTagValuesRequest struct {
	Db                   *string       `protobuf:"bytes,1,req,name=Db" json:"Db,omitempty"`
	PtIDs                []uint32      `protobuf:"varint,2,rep,name=PtIDs" json:"PtIDs,omitempty"`
	TagKeys              []*MapTagKeys `protobuf:"bytes,3,rep,name=TagKeys" json:"TagKeys,omitempty"`
	Condition            *string       `protobuf:"bytes,4,opt,name=Condition" json:"Condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ShowTagValuesRequest) Reset()         { *m = ShowTagValuesRequest{} }
func (m *ShowTagValuesRequest) String() string { return proto.CompactTextString(m) }
func (*ShowTagValuesRequest) ProtoMessage()    {}
func (*ShowTagValuesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaddb15866ce618, []int{12}
}
func (m *ShowTagValuesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowTagValuesRequest.Unmarshal(m, b)
}
func (m *ShowTagValuesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowTagValuesRequest.Marshal(b, m, deterministic)
}
func (m *ShowTagValuesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowTagValuesRequest.Merge(m, src)
}
func (m *ShowTagValuesRequest) XXX_Size() int {
	return xxx_messageInfo_ShowTagValuesRequest.Size(m)
}
func (m *ShowTagValuesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowTagValuesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShowTagValuesRequest proto.InternalMessageInfo

func (m *ShowTagValuesRequest) GetDb() string {
	if m != nil && m.Db != nil {
		return *m.Db
	}
	return ""
}

func (m *ShowTagValuesRequest) GetPtIDs() []uint32 {
	if m != nil {
		return m.PtIDs
	}
	return nil
}

func (m *ShowTagValuesRequest) GetTagKeys() []*MapTagKeys {
	if m != nil {
		return m.TagKeys
	}
	return nil
}

func (m *ShowTagValuesRequest) GetCondition() string {
	if m != nil && m.Condition != nil {
		return *m.Condition
	}
	return ""
}

type ShowTagValuesResponse struct {
	Err                  *string           `protobuf:"bytes,1,opt,name=Err" json:"Err,omitempty"`
	Values               []*TagValuesSlice `protobuf:"bytes,2,rep,name=Values" json:"Values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ShowTagValuesResponse) Reset()         { *m = ShowTagValuesResponse{} }
func (m *ShowTagValuesResponse) String() string { return proto.CompactTextString(m) }
func (*ShowTagValuesResponse) ProtoMessage()    {}
func (*ShowTagValuesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaddb15866ce618, []int{13}
}
func (m *ShowTagValuesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowTagValuesResponse.Unmarshal(m, b)
}
func (m *ShowTagValuesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowTagValuesResponse.Marshal(b, m, deterministic)
}
func (m *ShowTagValuesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowTagValuesResponse.Merge(m, src)
}
func (m *ShowTagValuesResponse) XXX_Size() int {
	return xxx_messageInfo_ShowTagValuesResponse.Size(m)
}
func (m *ShowTagValuesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowTagValuesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShowTagValuesResponse proto.InternalMessageInfo

func (m *ShowTagValuesResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

func (m *ShowTagValuesResponse) GetValues() []*TagValuesSlice {
	if m != nil {
		return m.Values
	}
	return nil
}

type MapTagKeys struct {
	Measurement          *string  `protobuf:"bytes,1,req,name=Measurement" json:"Measurement,omitempty"`
	Keys                 []string `protobuf:"bytes,2,rep,name=Keys" json:"Keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapTagKeys) Reset()         { *m = MapTagKeys{} }
func (m *MapTagKeys) String() string { return proto.CompactTextString(m) }
func (*MapTagKeys) ProtoMessage()    {}
func (*MapTagKeys) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaddb15866ce618, []int{14}
}
func (m *MapTagKeys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapTagKeys.Unmarshal(m, b)
}
func (m *MapTagKeys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapTagKeys.Marshal(b, m, deterministic)
}
func (m *MapTagKeys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapTagKeys.Merge(m, src)
}
func (m *MapTagKeys) XXX_Size() int {
	return xxx_messageInfo_MapTagKeys.Size(m)
}
func (m *MapTagKeys) XXX_DiscardUnknown() {
	xxx_messageInfo_MapTagKeys.DiscardUnknown(m)
}

var xxx_messageInfo_MapTagKeys proto.InternalMessageInfo

func (m *MapTagKeys) GetMeasurement() string {
	if m != nil && m.Measurement != nil {
		return *m.Measurement
	}
	return ""
}

func (m *MapTagKeys) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type TagValuesSlice struct {
	Measurement          *string  `protobuf:"bytes,1,req,name=Measurement" json:"Measurement,omitempty"`
	Keys                 []string `protobuf:"bytes,2,rep,name=Keys" json:"Keys,omitempty"`
	Values               []string `protobuf:"bytes,3,rep,name=Values" json:"Values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagValuesSlice) Reset()         { *m = TagValuesSlice{} }
func (m *TagValuesSlice) String() string { return proto.CompactTextString(m) }
func (*TagValuesSlice) ProtoMessage()    {}
func (*TagValuesSlice) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaddb15866ce618, []int{15}
}
func (m *TagValuesSlice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagValuesSlice.Unmarshal(m, b)
}
func (m *TagValuesSlice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagValuesSlice.Marshal(b, m, deterministic)
}
func (m *TagValuesSlice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagValuesSlice.Merge(m, src)
}
func (m *TagValuesSlice) XXX_Size() int {
	return xxx_messageInfo_TagValuesSlice.Size(m)
}
func (m *TagValuesSlice) XXX_DiscardUnknown() {
	xxx_messageInfo_TagValuesSlice.DiscardUnknown(m)
}

var xxx_messageInfo_TagValuesSlice proto.InternalMessageInfo

func (m *TagValuesSlice) GetMeasurement() string {
	if m != nil && m.Measurement != nil {
		return *m.Measurement
	}
	return ""
}

func (m *TagValuesSlice) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *TagValuesSlice) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type ExactCardinalityResponse struct {
	Cardinality          map[string]uint64 `protobuf:"bytes,1,rep,name=Cardinality" json:"Cardinality,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Err                  *string           `protobuf:"bytes,2,opt,name=Err" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ExactCardinalityResponse) Reset()         { *m = ExactCardinalityResponse{} }
func (m *ExactCardinalityResponse) String() string { return proto.CompactTextString(m) }
func (*ExactCardinalityResponse) ProtoMessage()    {}
func (*ExactCardinalityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaddb15866ce618, []int{16}
}
func (m *ExactCardinalityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExactCardinalityResponse.Unmarshal(m, b)
}
func (m *ExactCardinalityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExactCardinalityResponse.Marshal(b, m, deterministic)
}
func (m *ExactCardinalityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExactCardinalityResponse.Merge(m, src)
}
func (m *ExactCardinalityResponse) XXX_Size() int {
	return xxx_messageInfo_ExactCardinalityResponse.Size(m)
}
func (m *ExactCardinalityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExactCardinalityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExactCardinalityResponse proto.InternalMessageInfo

func (m *ExactCardinalityResponse) GetCardinality() map[string]uint64 {
	if m != nil {
		return m.Cardinality
	}
	return nil
}

func (m *ExactCardinalityResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type PtRequest struct {
	Pt                   *proto1.DbPt `protobuf:"bytes,1,req,name=Pt" json:"Pt,omitempty"`
	MigrateType          *int32       `protobuf:"varint,2,req,name=MigrateType" json:"MigrateType,omitempty"`
	OpId                 *uint64      `protobuf:"varint,3,req,name=OpId" json:"OpId,omitempty"`
	AliveConnId          *uint64      `protobuf:"varint,4,opt,name=AliveConnId" json:"AliveConnId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PtRequest) Reset()         { *m = PtRequest{} }
func (m *PtRequest) String() string { return proto.CompactTextString(m) }
func (*PtRequest) ProtoMessage()    {}
func (*PtRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaddb15866ce618, []int{17}
}
func (m *PtRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PtRequest.Unmarshal(m, b)
}
func (m *PtRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PtRequest.Marshal(b, m, deterministic)
}
func (m *PtRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PtRequest.Merge(m, src)
}
func (m *PtRequest) XXX_Size() int {
	return xxx_messageInfo_PtRequest.Size(m)
}
func (m *PtRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PtRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PtRequest proto.InternalMessageInfo

func (m *PtRequest) GetPt() *proto1.DbPt {
	if m != nil {
		return m.Pt
	}
	return nil
}

func (m *PtRequest) GetMigrateType() int32 {
	if m != nil && m.MigrateType != nil {
		return *m.MigrateType
	}
	return 0
}

func (m *PtRequest) GetOpId() uint64 {
	if m != nil && m.OpId != nil {
		return *m.OpId
	}
	return 0
}

func (m *PtRequest) GetAliveConnId() uint64 {
	if m != nil && m.AliveConnId != nil {
		return *m.AliveConnId
	}
	return 0
}

type PtResponse struct {
	Err                  *string  `protobuf:"bytes,1,opt,name=Err" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PtResponse) Reset()         { *m = PtResponse{} }
func (m *PtResponse) String() string { return proto.CompactTextString(m) }
func (*PtResponse) ProtoMessage()    {}
func (*PtResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaddb15866ce618, []int{18}
}
func (m *PtResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PtResponse.Unmarshal(m, b)
}
func (m *PtResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PtResponse.Marshal(b, m, deterministic)
}
func (m *PtResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PtResponse.Merge(m, src)
}
func (m *PtResponse) XXX_Size() int {
	return xxx_messageInfo_PtResponse.Size(m)
}
func (m *PtResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PtResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PtResponse proto.InternalMessageInfo

func (m *PtResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type QueryExeInfo struct {
	QueryID              *uint64  `protobuf:"varint,1,req,name=QueryID" json:"QueryID,omitempty"`
	Stmt                 *string  `protobuf:"bytes,2,req,name=Stmt" json:"Stmt,omitempty"`
	Database             *string  `protobuf:"bytes,3,req,name=Database" json:"Database,omitempty"`
	BeginTime            *int64   `protobuf:"varint,4,req,name=BeginTime" json:"BeginTime,omitempty"`
	RunState             *int32   `protobuf:"varint,5,req,name=RunState" json:"RunState,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryExeInfo) Reset()         { *m = QueryExeInfo{} }
func (m *QueryExeInfo) String() string { return proto.CompactTextString(m) }
func (*QueryExeInfo) ProtoMessage()    {}
func (*QueryExeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaddb15866ce618, []int{19}
}
func (m *QueryExeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryExeInfo.Unmarshal(m, b)
}
func (m *QueryExeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryExeInfo.Marshal(b, m, deterministic)
}
func (m *QueryExeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryExeInfo.Merge(m, src)
}
func (m *QueryExeInfo) XXX_Size() int {
	return xxx_messageInfo_QueryExeInfo.Size(m)
}
func (m *QueryExeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryExeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_QueryExeInfo proto.InternalMessageInfo

func (m *QueryExeInfo) GetQueryID() uint64 {
	if m != nil && m.QueryID != nil {
		return *m.QueryID
	}
	return 0
}

func (m *QueryExeInfo) GetStmt() string {
	if m != nil && m.Stmt != nil {
		return *m.Stmt
	}
	return ""
}

func (m *QueryExeInfo) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *QueryExeInfo) GetBeginTime() int64 {
	if m != nil && m.BeginTime != nil {
		return *m.BeginTime
	}
	return 0
}

func (m *QueryExeInfo) GetRunState() int32 {
	if m != nil && m.RunState != nil {
		return *m.RunState
	}
	return 0
}

type ShowQueriesResponse struct {
	QueryExeInfos        []*QueryExeInfo `protobuf:"bytes,1,rep,name=QueryExeInfos" json:"QueryExeInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ShowQueriesResponse) Reset()         { *m = ShowQueriesResponse{} }
func (m *ShowQueriesResponse) String() string { return proto.CompactTextString(m) }
func (*ShowQueriesResponse) ProtoMessage()    {}
func (*ShowQueriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaddb15866ce618, []int{20}
}
func (m *ShowQueriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowQueriesResponse.Unmarshal(m, b)
}
func (m *ShowQueriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowQueriesResponse.Marshal(b, m, deterministic)
}
func (m *ShowQueriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowQueriesResponse.Merge(m, src)
}
func (m *ShowQueriesResponse) XXX_Size() int {
	return xxx_messageInfo_ShowQueriesResponse.Size(m)
}
func (m *ShowQueriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowQueriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShowQueriesResponse proto.InternalMessageInfo

func (m *ShowQueriesResponse) GetQueryExeInfos() []*QueryExeInfo {
	if m != nil {
		return m.QueryExeInfos
	}
	return nil
}

type KillQueryRequest struct {
	QueryID              *uint64  `protobuf:"varint,1,req,name=QueryID" json:"QueryID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillQueryRequest) Reset()         { *m = KillQueryRequest{} }
func (m *KillQueryRequest) String() string { return proto.CompactTextString(m) }
func (*KillQueryRequest) ProtoMessage()    {}
func (*KillQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaddb15866ce618, []int{21}
}
func (m *KillQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillQueryRequest.Unmarshal(m, b)
}
func (m *KillQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillQueryRequest.Marshal(b, m, deterministic)
}
func (m *KillQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillQueryRequest.Merge(m, src)
}
func (m *KillQueryRequest) XXX_Size() int {
	return xxx_messageInfo_KillQueryRequest.Size(m)
}
func (m *KillQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KillQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KillQueryRequest proto.InternalMessageInfo

func (m *KillQueryRequest) GetQueryID() uint64 {
	if m != nil && m.QueryID != nil {
		return *m.QueryID
	}
	return 0
}

type KillQueryResponse struct {
	ErrCode              *uint32  `protobuf:"varint,1,opt,name=ErrCode" json:"ErrCode,omitempty"`
	ErrMsg               *string  `protobuf:"bytes,2,opt,name=ErrMsg" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillQueryResponse) Reset()         { *m = KillQueryResponse{} }
func (m *KillQueryResponse) String() string { return proto.CompactTextString(m) }
func (*KillQueryResponse) ProtoMessage()    {}
func (*KillQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaddb15866ce618, []int{22}
}
func (m *KillQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillQueryResponse.Unmarshal(m, b)
}
func (m *KillQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillQueryResponse.Marshal(b, m, deterministic)
}
func (m *KillQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillQueryResponse.Merge(m, src)
}
func (m *KillQueryResponse) XXX_Size() int {
	return xxx_messageInfo_KillQueryResponse.Size(m)
}
func (m *KillQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KillQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KillQueryResponse proto.InternalMessageInfo

func (m *KillQueryResponse) GetErrCode() uint32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *KillQueryResponse) GetErrMsg() string {
	if m != nil && m.ErrMsg != nil {
		return *m.ErrMsg
	}
	return ""
}

type SegregateNodeRequest struct {
	NodeId               *uint64  `protobuf:"varint,1,req,name=NodeId" json:"NodeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SegregateNodeRequest) Reset()         { *m = SegregateNodeRequest{} }
func (m *SegregateNodeRequest) String() string { return proto.CompactTextString(m) }
func (*SegregateNodeRequest) ProtoMessage()    {}
func (*SegregateNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaddb15866ce618, []int{23}
}
func (m *SegregateNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegregateNodeRequest.Unmarshal(m, b)
}
func (m *SegregateNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegregateNodeRequest.Marshal(b, m, deterministic)
}
func (m *SegregateNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegregateNodeRequest.Merge(m, src)
}
func (m *SegregateNodeRequest) XXX_Size() int {
	return xxx_messageInfo_SegregateNodeRequest.Size(m)
}
func (m *SegregateNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SegregateNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SegregateNodeRequest proto.InternalMessageInfo

func (m *SegregateNodeRequest) GetNodeId() uint64 {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return 0
}

type SegregateNodeResponse struct {
	Err                  *string  `protobuf:"bytes,1,opt,name=Err" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SegregateNodeResponse) Reset()         { *m = SegregateNodeResponse{} }
func (m *SegregateNodeResponse) String() string { return proto.CompactTextString(m) }
func (*SegregateNodeResponse) ProtoMessage()    {}
func (*SegregateNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaddb15866ce618, []int{24}
}
func (m *SegregateNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegregateNodeResponse.Unmarshal(m, b)
}
func (m *SegregateNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegregateNodeResponse.Marshal(b, m, deterministic)
}
func (m *SegregateNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegregateNodeResponse.Merge(m, src)
}
func (m *SegregateNodeResponse) XXX_Size() int {
	return xxx_messageInfo_SegregateNodeResponse.Size(m)
}
func (m *SegregateNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SegregateNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SegregateNodeResponse proto.InternalMessageInfo

func (m *SegregateNodeResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*SeriesKeysRequest)(nil), "netstorage.data.SeriesKeysRequest")
	proto.RegisterType((*SeriesKeysResponse)(nil), "netstorage.data.SeriesKeysResponse")
	proto.RegisterType((*ShowTagKeysRequest)(nil), "netstorage.data.ShowTagKeysRequest")
	proto.RegisterType((*ShowTagKeysResponse)(nil), "netstorage.data.ShowTagKeysResponse")
	proto.RegisterType((*CreateDataBaseRequest)(nil), "netstorage.data.CreateDataBaseRequest")
	proto.RegisterType((*CreateDataBaseResponse)(nil), "netstorage.data.CreateDataBaseResponse")
	proto.RegisterType((*SysCtrlRequest)(nil), "netstorage.data.SysCtrlRequest")
	proto.RegisterMapType((map[string]string)(nil), "netstorage.data.SysCtrlRequest.ParamEntry")
	proto.RegisterType((*SysCtrlResponse)(nil), "netstorage.data.SysCtrlResponse")
	proto.RegisterMapType((map[string]string)(nil), "netstorage.data.SysCtrlResponse.ResultEntry")
	proto.RegisterType((*GetShardSplitPointsRequest)(nil), "netstorage.data.GetShardSplitPointsRequest")
	proto.RegisterType((*GetShardSplitPointsResponse)(nil), "netstorage.data.GetShardSplitPointsResponse")
	proto.RegisterType((*DeleteRequest)(nil), "netstorage.data.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "netstorage.data.DeleteResponse")
	proto.RegisterType((*ShowTagValuesRequest)(nil), "netstorage.data.ShowTagValuesRequest")
	proto.RegisterType((*ShowTagValuesResponse)(nil), "netstorage.data.ShowTagValuesResponse")
	proto.RegisterType((*MapTagKeys)(nil), "netstorage.data.MapTagKeys")
	proto.RegisterType((*TagValuesSlice)(nil), "netstorage.data.TagValuesSlice")
	proto.RegisterType((*ExactCardinalityResponse)(nil), "netstorage.data.ExactCardinalityResponse")
	proto.RegisterMapType((map[string]uint64)(nil), "netstorage.data.ExactCardinalityResponse.CardinalityEntry")
	proto.RegisterType((*PtRequest)(nil), "netstorage.data.PtRequest")
	proto.RegisterType((*PtResponse)(nil), "netstorage.data.PtResponse")
	proto.RegisterType((*QueryExeInfo)(nil), "netstorage.data.QueryExeInfo")
	proto.RegisterType((*ShowQueriesResponse)(nil), "netstorage.data.ShowQueriesResponse")
	proto.RegisterType((*KillQueryRequest)(nil), "netstorage.data.KillQueryRequest")
	proto.RegisterType((*KillQueryResponse)(nil), "netstorage.data.KillQueryResponse")
	proto.RegisterType((*SegregateNodeRequest)(nil), "netstorage.data.SegregateNodeRequest")
	proto.RegisterType((*SegregateNodeResponse)(nil), "netstorage.data.SegregateNodeResponse")
}

func init() { proto.RegisterFile("lib/netstorage/data/data.proto", fileDescriptor_2aaddb15866ce618) }

var fileDescriptor_2aaddb15866ce618 = []byte{
	// 973 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xd6, 0xce, 0x3a, 0x09, 0x3e, 0x6e, 0xdc, 0x64, 0x9b, 0x44, 0x2b, 0x07, 0xc2, 0x6a, 0x25,
	0x24, 0x53, 0x55, 0x1b, 0x29, 0x12, 0xa2, 0x14, 0xa9, 0x80, 0x7f, 0x54, 0x59, 0x95, 0xc1, 0x1d,
	0x47, 0x5c, 0x54, 0x08, 0x34, 0xce, 0x9e, 0xba, 0xab, 0xae, 0x77, 0x97, 0x99, 0x71, 0x89, 0x05,
	0x17, 0xbc, 0x42, 0x79, 0x00, 0xae, 0x78, 0x1a, 0x9e, 0x0a, 0xcd, 0xcf, 0xda, 0x6b, 0xbb, 0x16,
	0x0a, 0x37, 0xdc, 0xac, 0xe6, 0x7c, 0x7b, 0x7e, 0xbe, 0x39, 0xf3, 0x9d, 0x19, 0xb8, 0x48, 0x93,
	0xc9, 0x65, 0x86, 0x52, 0xc8, 0x9c, 0xb3, 0x29, 0x5e, 0xc6, 0x4c, 0x32, 0xfd, 0x89, 0x0a, 0x9e,
	0xcb, 0xdc, 0xbb, 0xbf, 0xfa, 0x17, 0x29, 0xb8, 0xf5, 0x49, 0x5e, 0x60, 0xf6, 0x93, 0xe0, 0x37,
	0x97, 0x49, 0xf6, 0x2a, 0x9d, 0xdf, 0x5e, 0xce, 0x50, 0xb2, 0x4b, 0xed, 0xac, 0x97, 0x26, 0x2e,
	0xfc, 0x15, 0x8e, 0xc7, 0xc8, 0x13, 0x14, 0xcf, 0x71, 0x21, 0x28, 0xfe, 0x3c, 0x47, 0x21, 0xbd,
	0x26, 0x90, 0xde, 0xc4, 0x77, 0x02, 0xd2, 0xae, 0x53, 0xd2, 0x9b, 0x78, 0x27, 0xb0, 0x37, 0x92,
	0x83, 0x9e, 0xf0, 0x49, 0xe0, 0xb6, 0x0f, 0xa9, 0x31, 0xbc, 0x10, 0xee, 0x0d, 0x91, 0x89, 0x39,
	0xc7, 0x19, 0x66, 0x52, 0xf8, 0x6e, 0xe0, 0xb6, 0xeb, 0x74, 0x0d, 0xf3, 0x3e, 0x84, 0xfa, 0x4d,
	0x9e, 0xc5, 0x89, 0x4c, 0xf2, 0xcc, 0xaf, 0x05, 0x4e, 0xbb, 0x4e, 0x57, 0x40, 0xf8, 0x14, 0xbc,
	0x6a, 0x71, 0x51, 0xe4, 0x99, 0x40, 0xef, 0x0c, 0xf6, 0x0d, 0xea, 0x3b, 0x3a, 0xa3, 0xb5, 0xbc,
	0x23, 0x70, 0xfb, 0x9c, 0xfb, 0x44, 0x67, 0x51, 0xcb, 0xf0, 0x37, 0xf0, 0xc6, 0xaf, 0xf3, 0x5f,
	0xae, 0xd9, 0xf4, 0xff, 0x60, 0xff, 0x15, 0x3c, 0x58, 0xab, 0x7e, 0x67, 0xfa, 0xcf, 0xe0, 0xb4,
	0xcb, 0x91, 0x49, 0xec, 0x31, 0xc9, 0x3a, 0x4c, 0xe0, 0xae, 0x1d, 0x34, 0x81, 0x14, 0xd2, 0x27,
	0x01, 0x69, 0x1f, 0x52, 0x52, 0xe8, 0xff, 0xbc, 0xf0, 0x5d, 0xf3, 0x9f, 0x17, 0xe1, 0x43, 0x38,
	0xdb, 0x4c, 0x64, 0xc9, 0xd8, 0xa2, 0xce, 0xaa, 0xe8, 0x9f, 0x0e, 0x34, 0xc7, 0x0b, 0xd1, 0x95,
	0x3c, 0x2d, 0xcb, 0x1d, 0x81, 0x3b, 0xcc, 0x63, 0x5b, 0x4f, 0x2d, 0xbd, 0xaf, 0x61, 0x6f, 0xc4,
	0x38, 0x9b, 0xe9, 0x96, 0x35, 0xae, 0x1e, 0x46, 0x1b, 0xea, 0x8a, 0xd6, 0x33, 0x44, 0xda, 0xb9,
	0x9f, 0x49, 0xbe, 0xa0, 0x26, 0xb0, 0xf5, 0x18, 0x60, 0x05, 0xaa, 0x0a, 0x6f, 0x70, 0x51, 0xd2,
	0x78, 0x83, 0x0b, 0x75, 0x28, 0x6f, 0x59, 0x3a, 0x47, 0xdb, 0x0f, 0x63, 0x3c, 0x21, 0x8f, 0x9d,
	0xf0, 0x2f, 0x07, 0xee, 0x2f, 0xd3, 0x6f, 0x6e, 0x83, 0xd8, 0x6d, 0x78, 0x3d, 0xd8, 0xa7, 0x28,
	0xe6, 0xa9, 0xb4, 0x14, 0x1f, 0xed, 0xa6, 0x68, 0x72, 0x44, 0xc6, 0xdd, 0x90, 0xb4, 0xb1, 0xad,
	0x2f, 0xa0, 0x51, 0x81, 0xef, 0x44, 0xb3, 0x80, 0xd6, 0x33, 0x94, 0xe3, 0xd7, 0x8c, 0xc7, 0xe3,
	0x22, 0x4d, 0xe4, 0x28, 0x4f, 0x32, 0xb9, 0xa6, 0xc1, 0xce, 0xf2, 0x04, 0x3b, 0x9e, 0x07, 0x35,
	0x25, 0x3b, 0x7b, 0x86, 0x7a, 0xed, 0xf9, 0x70, 0xa0, 0xc3, 0x07, 0x3d, 0x7d, 0x94, 0x35, 0x5a,
	0x9a, 0xaa, 0xea, 0x20, 0xbe, 0x45, 0xe1, 0xd7, 0x02, 0xb7, 0xed, 0x52, 0x63, 0x84, 0x2f, 0xe0,
	0xfc, 0xbd, 0x15, 0x6d, 0x8f, 0x02, 0x68, 0x54, 0x60, 0x2b, 0xbe, 0x2a, 0xf4, 0x1e, 0x05, 0xbe,
	0x73, 0xe0, 0xb0, 0x87, 0x29, 0x4a, 0xdc, 0x45, 0xbc, 0x09, 0x84, 0x16, 0x36, 0x84, 0xd0, 0x42,
	0x6b, 0x45, 0x48, 0xdf, 0x35, 0x39, 0x86, 0x42, 0x7a, 0x2d, 0xf8, 0xc0, 0xf2, 0x36, 0x7c, 0x6b,
	0x74, 0x69, 0x7b, 0x17, 0x00, 0x26, 0xfd, 0xf5, 0xa2, 0x40, 0x7f, 0x2f, 0x20, 0xed, 0x3d, 0x5a,
	0x41, 0x6c, 0x5b, 0x62, 0x7f, 0x3f, 0x70, 0x6c, 0x5b, 0xe2, 0x30, 0x84, 0x66, 0x49, 0x69, 0xa7,
	0x88, 0xdf, 0x39, 0x70, 0x62, 0x67, 0xef, 0x7b, 0x75, 0x22, 0x77, 0x9c, 0xfd, 0xcf, 0xe0, 0xc0,
	0x4e, 0xad, 0x1e, 0xfb, 0xc6, 0xd5, 0xf9, 0x96, 0x7a, 0x86, 0xac, 0x28, 0x07, 0xbb, 0xf4, 0x55,
	0xd7, 0x41, 0x77, 0xf3, 0x3a, 0x58, 0x02, 0xe1, 0x04, 0x4e, 0x37, 0x28, 0xed, 0xa2, 0xef, 0x7d,
	0x0e, 0xfb, 0xc6, 0xc7, 0x8a, 0xf7, 0xe3, 0xad, 0xf2, 0xcb, 0x2c, 0xe3, 0x34, 0xb9, 0x41, 0x6a,
	0xdd, 0xc3, 0x0e, 0xc0, 0x8a, 0x98, 0x3a, 0xf1, 0xca, 0x75, 0x65, 0x77, 0x5d, 0x85, 0x54, 0x7f,
	0xf5, 0x2e, 0x89, 0x16, 0x83, 0x5e, 0x87, 0x3f, 0x42, 0x73, 0x3d, 0xfb, 0x7f, 0xcb, 0xa3, 0xee,
	0x39, 0xbb, 0x09, 0x73, 0x75, 0x96, 0x1c, 0xff, 0x76, 0xc0, 0xef, 0xdf, 0xb2, 0x1b, 0xd9, 0x65,
	0x3c, 0x4e, 0x32, 0x96, 0x26, 0x72, 0xb1, 0xec, 0xc5, 0x0f, 0xd0, 0xa8, 0xc0, 0x5a, 0xa4, 0x8d,
	0xab, 0x27, 0x5b, 0xdb, 0xdf, 0x15, 0x1f, 0x55, 0x30, 0x33, 0xc9, 0xd5, 0x74, 0xdb, 0x02, 0x6f,
	0x3d, 0x85, 0xa3, 0xcd, 0x90, 0x7f, 0x9b, 0xf2, 0x5a, 0x75, 0xca, 0x7f, 0x77, 0xa0, 0x3e, 0x92,
	0xa5, 0xba, 0xce, 0x81, 0x8c, 0x4c, 0x7f, 0x1a, 0x57, 0x0d, 0xf3, 0x80, 0x46, 0xbd, 0xc9, 0x48,
	0x52, 0x32, 0x92, 0xba, 0x8b, 0xc9, 0x94, 0x33, 0x2b, 0x76, 0xa2, 0xc5, 0x5e, 0x85, 0x54, 0x17,
	0xbf, 0x2b, 0x06, 0xb1, 0x9d, 0x76, 0xbd, 0x56, 0x51, 0xdf, 0xa4, 0xc9, 0x5b, 0xec, 0xe6, 0x59,
	0x36, 0x88, 0xb5, 0xaa, 0x6a, 0xb4, 0x0a, 0x85, 0x17, 0x00, 0x8a, 0xc1, 0xce, 0x59, 0xf8, 0xc3,
	0x81, 0x7b, 0x2f, 0xe6, 0xc8, 0x17, 0xfd, 0x5b, 0x1c, 0x64, 0xaf, 0x72, 0x75, 0xaf, 0x68, 0x7b,
	0xd0, 0xd3, 0x54, 0x6b, 0xb4, 0x34, 0x15, 0x81, 0xb1, 0x9c, 0x99, 0x97, 0xa4, 0x4e, 0xf5, 0x5a,
	0x8d, 0xaf, 0x7a, 0x35, 0x26, 0x4c, 0xa0, 0x7d, 0x51, 0x96, 0xb6, 0x12, 0x7c, 0x07, 0xa7, 0x49,
	0x76, 0x9d, 0xcc, 0xd0, 0xaf, 0x05, 0xa4, 0xed, 0xd2, 0x15, 0xa0, 0x22, 0xe9, 0x3c, 0x1b, 0x4b,
	0x26, 0xcb, 0xd1, 0x5e, 0xda, 0xe1, 0x4b, 0xf3, 0x36, 0xaa, 0xc2, 0x49, 0x65, 0x14, 0xba, 0x70,
	0x58, 0xa5, 0x2a, 0xac, 0x00, 0x3e, 0xda, 0x12, 0x40, 0xd5, 0x8b, 0xae, 0xc7, 0x84, 0x8f, 0xe0,
	0xe8, 0x79, 0x92, 0xa6, 0x1a, 0x2c, 0x4f, 0x66, 0xe7, 0x9e, 0xc3, 0x3e, 0x1c, 0x57, 0xbc, 0x2d,
	0x0f, 0x1f, 0x0e, 0xfa, 0x9c, 0x77, 0xf3, 0x18, 0x75, 0x27, 0x0f, 0x69, 0x69, 0x2a, 0x55, 0xf7,
	0x39, 0x1f, 0x8a, 0xa9, 0x55, 0x91, 0xb5, 0xc2, 0x08, 0x4e, 0xc6, 0x38, 0xe5, 0x38, 0x65, 0x12,
	0xbf, 0xcd, 0xe3, 0xe5, 0x7d, 0x79, 0x06, 0xfb, 0xca, 0x1c, 0xc4, 0xb6, 0xae, 0xb5, 0xc2, 0x4f,
	0xe1, 0x74, 0xc3, 0x7f, 0xd7, 0x01, 0x76, 0x1e, 0xbc, 0x3c, 0x8e, 0xbe, 0xdc, 0x68, 0xc0, 0x3f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x61, 0x72, 0x20, 0xab, 0xf0, 0x09, 0x00, 0x00,
}
